### ISSUE TITLE
Syntax error in question/type/javaunittest/lang/de/qtype_javaunittest.php

### ISSUE THREAD

**Issue by nitro2010-zz** [tuttorsOfTheTUBerlin/javaunittest#3]
PHP Parse error:  syntax error, unexpected '$string' (T_VARIABLE) in /opt/lampp/htdocs/moodle/question/type/javaunittest/lang/de/qtype_javaunittest.php on line 84
18:36:28 
18:36:28 Parse error: syntax error, unexpected '$string' (T_VARIABLE) in /opt/lampp/htdocs/moodle/question/type/javaunittest/lang/de/qtype_javaunittest.php on line 84
18:36:28 Errors parsing /opt/lampp/htdocs/moodle/question/type/javaunittest/lang/de/qtype_javaunittest.php

Please correct this line in file:

$string['hiddenfails'] = 'Es sind {$a} weitere Tests fehlgeschlagen.'

add on te end ';'

**Comment by mrumler** [comment]
Thank you, fixed in commit 06c53a28f1c62d7a74b5d3180f5ca43e574187b0 .
