### ISSUE TITLE
Support für Moodle 3.1

### ISSUE THREAD

**Issue by jtuttas** [tuttorsOfTheTUBerlin/javaunittest#6]
Hallo,
ich denke ich kann auch auf deutsch schreiben, oder? 

Unsere Moodle Installation ist jetzt auf der Version 3.1. Leider erhalten wir beim Questiontype Junit eine Fehlermeldung, obwohl dieser unter der Version 2.9 gut funktionierte ! Beim Ausführen eines Test erhalte ich die Fehlermeldung "JUNIT TEST FILE ERROR: Test kann nicht ausgeführt werden. Die eingegebene Antwort ist nicht mit der Testklasse kompatibel oder die Testklasse konnte nicht kompiliert werden."

Nun weiß ich leider nicht ob es an unserem System liegt (Ubuntu 12.04) oder an dem Plugin, daher schon mal die Frage, ob das Plugin schon mal auf einem Moodle 3.1 System lief?

Danke und Gruß!

jtuttas

**Comment by jtuttas** [comment]
Sorry, war wohl unser Problem, geht super mit 3.1!

**Comment by mrumler** [comment]
Hallo jtuttas,
wunderbar. Dann weiterhin gutes Gelingen! :) Weiteres Feedback gern!
